version: "3.9"
services:
  fibo:
    build: .
    links:
      - postgres
      - jaeger
    ports:
      - 8080:8080
    environment:
      PORT: "8080"
      FIBO_PGUSER: ${POSTGRES_USER}
      FIBO_PGPASSWORD: ${POSTGRES_PASSWORD}
      FIBO_PGHOST: postgres
      FIBO_PGPORT: 5432
      FIBO_PGDB: ${POSTGRES_DB}
      JAEGER_AGENT_HOST: jaeger
    depends_on:
      - postgres
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    ports:
      - 15432:5432 # a debugging port to use psql and manually inspect the database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgvolume01:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - 14271:14271/tcp # health check
      - 16686:16686/tcp # jaeger front-end UI
      - 6831:6831/udp # jaeger.thrift compact ingestion
volumes:
  pgvolume01: {}