version: "3.9"
services:
  fibo:
    build: .
    links:
      - postgres
    ports:
      - 8080:8080
    environment:
      PORT: "8080"
      FIBO_PGUSER: ${POSTGRES_USER}
      FIBO_PGPASSWORD: ${POSTGRES_PASSWORD}
      FIBO_PGHOST: postgres
      FIBO_PGPORT: 5432
      FIBO_PGDB: ${POSTGRES_DB}
    depends_on:
      - postgres
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    ports:
      - 15432:5432 # a debugging port to use psql and manually inspect the database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgvolume01:/var/lib/postgresql/data
volumes:
  pgvolume01: {}